version: '3'

services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  todos:
    image: todos
    restart: always
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - '8081:8081'
    environment:
      - DB_PORT=5432
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_PASSWORD=postgres
      - DB_USERNAME=postgres

  users:
    image: users
    restart: always
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - '9000:9000'
    environment:
      - DB_PORT=5432
      - DB_HOST=postgres
      - DB_NAME=postgres
      - DB_PASSWORD=postgres
      - DB_USERNAME=postgres

  wrapper:
    image: wrapper
    restart: always
    depends_on:
      - users
      - todos
    links:
      - users
      - todos
    ports:
      - '8082:8082'
    environment:
      - USERS_SERVICE_URL=users:9000
      - TODOS_SERVICE_URL=http://todos:8081/todos