# Todos

### GET all
GET http://localhost:8081/todos
Accept: application/json

### GET by id
GET http://localhost:8081/todos/1
Accept: application/json

### POST user
POST http://localhost:8081/todos
Content-Type: application/json

{
  "description": "test",
  "user_id": 1
}

### PUT user
PUT http://localhost:8081/todos/1
Content-Type: application/json

{
  "user_id": 1
}

### Delete user
DELETE http://localhost:8081/todos/2
Content-Type: application/json


### GET root
GET http://localhost:8080/
Accept: application/json


# WRAPPER #

### GET all todos
GET http://{{host}}/todos
Accept: application/json
